"""empty message

Revision ID: 10b9fa9307f8
Revises: 45e95258c932
Create Date: 2023-09-26 13:51:04.525895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b9fa9307f8'
down_revision = '45e95258c932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_flows', sa.Column('id_owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prompt_flows', 'profiles', ['id_owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_flows', type_='foreignkey')
    op.drop_column('prompt_flows', 'id_owner')
    # ### end Alembic commands ###
