"""empty message

Revision ID: 1a54c3e307e2
Revises: 9508d38981d5
Create Date: 2023-06-29 11:27:54.846969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a54c3e307e2'
down_revision = '9508d38981d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prompt_flow', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_prompt_flow'], ['prompt_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('score_name', sa.String(), nullable=True),
    sa.Column('score_value', sa.Float(), nullable=True),
    sa.Column('score_min', sa.Float(), nullable=True),
    sa.Column('score_max', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_run_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prompt_run', sa.Integer(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id_node', sa.Integer(), nullable=True),
    sa.Column('id_text', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_node'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['id_prompt_run'], ['prompt_runs.id'], ),
    sa.ForeignKeyConstraint(['id_text'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prompt_run_item', sa.Integer(), nullable=True),
    sa.Column('id_profile', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_min', sa.Integer(), nullable=True),
    sa.Column('rating_max', sa.Integer(), nullable=True),
    sa.Column('id_text', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_profile'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['id_prompt_run_item'], ['prompt_run_items.id'], ),
    sa.ForeignKeyConstraint(['id_text'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedbacks')
    op.drop_table('prompt_run_items')
    op.drop_table('sentiment_scores')
    op.drop_table('prompt_runs')
    # ### end Alembic commands ###
