"""empty message

Revision ID: 1ab299f454cf
Revises: 6abe600104b5
Create Date: 2023-11-20 12:11:09.394377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab299f454cf'
down_revision = '6abe600104b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('body_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items', 'body_text')
    # ### end Alembic commands ###
