"""empty message

Revision ID: 28ce67342c9a
Revises: a9127f2b8fa5
Create Date: 2023-08-11 12:24:14.179476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ce67342c9a'
down_revision = 'a9127f2b8fa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_owner', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_deck_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_deck', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_deck'], ['prompt_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_deck_columns')
    op.drop_table('prompt_decks')
    # ### end Alembic commands ###
