"""empty message

Revision ID: 2985e279047f
Revises: 361ffc59eacd
Create Date: 2024-01-30 10:14:09.560694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2985e279047f'
down_revision = '361ffc59eacd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_item_personalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_media_item', sa.Integer(), nullable=True),
    sa.Column('id_profile', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_media_item'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['id_profile'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media_item_predictions', sa.Column('prediction_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_item_predictions', 'prediction_name')
    op.drop_table('media_item_personalizations')
    # ### end Alembic commands ###
