"""empty message

Revision ID: 2f26dff87add
Revises: ff39aa49904b
Create Date: 2023-10-20 12:02:49.777265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f26dff87add'
down_revision = 'ff39aa49904b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_default')
    # ### end Alembic commands ###
