"""empty message

Revision ID: 30f67deb3e6a
Revises: 3556a9a1f86f
Create Date: 2023-10-12 09:56:34.566607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30f67deb3e6a'
down_revision = '3556a9a1f86f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('name', sa.String(), nullable=True))
    op.add_column('edges', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'payload')
    op.drop_column('edges', 'name')
    # ### end Alembic commands ###
