"""empty message

Revision ID: 3556a9a1f86f
Revises: 10b9fa9307f8
Create Date: 2023-09-26 18:14:36.523400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3556a9a1f86f'
down_revision = '10b9fa9307f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('prompt_deck_columns', sa.Column('key', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('prompt_deck_columns', 'key')
    
    # ### end Alembic commands ###
