"""empty message

Revision ID: 3ac6e43a319c
Revises: 92645fcacc2e
Create Date: 2023-09-18 15:45:46.506179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac6e43a319c'
down_revision = '92645fcacc2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('id_prompt_flow', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'edges', 'prompt_flows', ['id_prompt_flow'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'edges', type_='foreignkey')
    op.drop_column('edges', 'id_prompt_flow')
    # ### end Alembic commands ###
