"""empty message

Revision ID: 43cf26362e67
Revises: 5346f88f34ca
Create Date: 2023-07-06 18:47:02.056245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cf26362e67'
down_revision = '5346f88f34ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_flows', sa.Column('category', sa.String(), nullable=True))
    op.add_column('prompt_flows', sa.Column('subcategory', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_flows', 'subcategory')
    op.drop_column('prompt_flows', 'category')
    # ### end Alembic commands ###
