"""empty message

Revision ID: 45e95258c932
Revises: 457a2cc0f225
Create Date: 2023-09-26 13:29:43.355594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e95258c932'
down_revision = '457a2cc0f225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_flows', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_flows', 'version')
    # ### end Alembic commands ###
