"""empty message

Revision ID: 48bd35de6698
Revises: 2f26dff87add
Create Date: 2023-10-20 15:59:54.117921

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '48bd35de6698'
down_revision = '2f26dff87add'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_datums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id_profile', sa.Integer(), nullable=True),
    sa.Column('openai_category_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('openai_key_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('openai_value_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('id_run_item', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_profile'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['id_run_item'], ['prompt_run_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_datums')
    # ### end Alembic commands ###
