"""empty message

Revision ID: 5346f88f34ca
Revises: fdc3be5dc70f
Create Date: 2023-07-06 17:54:41.458925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5346f88f34ca'
down_revision = 'fdc3be5dc70f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_flows', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_flows', 'payload')
    # ### end Alembic commands ###
