"""empty message

Revision ID: 575850f5e5de
Revises: ca8e361799ce
Create Date: 2023-11-23 17:34:49.329717

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '575850f5e5de'
down_revision = 'ca8e361799ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('openai_topic_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_feed_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_media_feed', sa.Integer(), nullable=True),
    sa.Column('id_media_topic', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_media_feed'], ['media_feeds.id'], ),
    sa.ForeignKeyConstraint(['id_media_topic'], ['media_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_feed_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_media_item', sa.Integer(), nullable=True),
    sa.Column('id_media_feed', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_media_feed'], ['media_feeds.id'], ),
    sa.ForeignKeyConstraint(['id_media_item'], ['media_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_feed_items')
    op.drop_table('media_feed_topics')
    op.drop_table('media_topics')
    op.drop_table('media_feeds')
    # ### end Alembic commands ###
