"""empty message

Revision ID: 5c5d3767349e
Revises: 9c1ee9aa5960
Create Date: 2023-10-26 14:51:51.600077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c5d3767349e'
down_revision = '9c1ee9aa5960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('prompts', sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # op.add_column('prompts', sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('prompts', 'output_payload')
    # op.drop_column('prompts', 'input_payload')
    # ### end Alembic commands ###
    pass
