"""empty message

Revision ID: 8009339250c0
Revises: 1ab299f454cf
Create Date: 2023-11-20 15:54:20.465020

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = '8009339250c0'
down_revision = '1ab299f454cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('openai_tag_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_media_item', sa.Integer(), nullable=True),
    sa.Column('id_media_tag', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_media_item'], ['media_items.id'], ),
    sa.ForeignKeyConstraint(['id_media_tag'], ['media_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_item_tags')
    op.drop_table('media_tags')
    # ### end Alembic commands ###
