"""empty message

Revision ID: 92645fcacc2e
Revises: b9facf0c0490
Create Date: 2023-08-21 15:12:29.391271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92645fcacc2e'
down_revision = 'b9facf0c0490'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
