"""empty message

Revision ID: 9508d38981d5
Revises: c0eef6589971
Create Date: 2023-06-29 10:56:19.766855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9508d38981d5'
down_revision = 'c0eef6589971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_node_id', sa.Integer(), nullable=True),
    sa.Column('end_node_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['end_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['start_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nodes', sa.Column('id_prompt', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nodes', 'prompts', ['id_prompt'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='foreignkey')
    op.drop_column('nodes', 'id_prompt')
    op.drop_table('edges')
    # ### end Alembic commands ###
