"""empty message

Revision ID: 9c1d6c2cd8ba
Revises: bd576cf0179d
Create Date: 2024-01-02 13:21:52.152753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1d6c2cd8ba'
down_revision = 'bd576cf0179d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_runs', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_runs', 'completed')
    # ### end Alembic commands ###
