"""empty message

Revision ID: 9c1ee9aa5960
Revises: db93c24c2f22
Create Date: 2023-10-26 14:00:19.849378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1ee9aa5960'
down_revision = 'db93c24c2f22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_datums', sa.Column('kind', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_datums', 'kind')
    # ### end Alembic commands ###
