"""empty message

Revision ID: af8e00b262fb
Revises: 1fd407ae28d2
Create Date: 2023-07-25 22:21:38.928300

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'af8e00b262fb'
down_revision = '1fd407ae28d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('category', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('rawtext', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('text', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('openai_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'openai_embedding')
    op.drop_column('prompts', 'text')
    op.drop_column('prompts', 'rawtext')
    op.drop_column('prompts', 'subcategory')
    op.drop_column('prompts', 'category')
    # ### end Alembic commands ###
