"""empty message

Revision ID: b077c0ac4b2f
Revises: af8e00b262fb
Create Date: 2023-07-25 23:31:44.727920

"""
from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = 'b077c0ac4b2f'
down_revision = 'af8e00b262fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('system', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('openai_embedding_system', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'openai_embedding_system')
    op.drop_column('prompts', 'system')
    # ### end Alembic commands ###
