"""empty message

Revision ID: b3c140054f70
Revises: 91e0b6d7bbe5
Create Date: 2024-02-22 14:30:34.744432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c140054f70'
down_revision = '91e0b6d7bbe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_feeds', sa.Column('is_default', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_feeds', 'is_default')
    # ### end Alembic commands ###
