"""empty message

Revision ID: b94c8af1c184
Revises: b3c140054f70
Create Date: 2024-02-26 14:19:55.137229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b94c8af1c184'
down_revision = 'b3c140054f70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_item_personalizations', sa.Column('personalized_image_url', sa.String(), nullable=True))
    op.add_column('media_item_personalizations', sa.Column('personalized_title', sa.String(), nullable=True))
    op.add_column('media_item_personalizations', sa.Column('personalized_summary', sa.String(), nullable=True))
    op.add_column('media_item_personalizations', sa.Column('personalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('media_item_personalizations', sa.Column('personalized_tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_item_personalizations', 'personalized_tags')
    op.drop_column('media_item_personalizations', 'personalized_payload')
    op.drop_column('media_item_personalizations', 'personalized_summary')
    op.drop_column('media_item_personalizations', 'personalized_title')
    op.drop_column('media_item_personalizations', 'personalized_image_url')
    # ### end Alembic commands ###
