"""empty message

Revision ID: b9facf0c0490
Revises: f5f30f13b31d
Create Date: 2023-08-14 21:24:36.730126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9facf0c0490'
down_revision = 'f5f30f13b31d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prompt_deck_column_items_id_column_fkey', 'prompt_deck_column_items', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_deck_column_items', 'prompt_deck_columns', ['id_column'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_deck_column_items', type_='foreignkey')
    op.create_foreign_key('prompt_deck_column_items_id_column_fkey', 'prompt_deck_column_items', 'prompt_decks', ['id_column'], ['id'])
    # ### end Alembic commands ###
