"""empty message

Revision ID: ba68fae3729b
Revises: 48bd35de6698
Create Date: 2023-10-24 15:56:01.391767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba68fae3729b'
down_revision = '48bd35de6698'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_datum_context_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ranker', sa.Integer(), nullable=True),
    sa.Column('id_text', sa.Integer(), nullable=True),
    sa.Column('id_profile_datum', sa.Integer(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_profile_datum'], ['profile_datums.id'], ),
    sa.ForeignKeyConstraint(['id_ranker'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['id_text'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_datum_context_responses')
    # ### end Alembic commands ###
