"""empty message

Revision ID: bd576cf0179d
Revises: c7631b1f30b2
Create Date: 2023-12-04 12:13:37.869193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd576cf0179d'
down_revision = 'c7631b1f30b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_feeds', sa.Column('id_profile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media_feeds', 'profiles', ['id_profile'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_feeds', type_='foreignkey')
    op.drop_column('media_feeds', 'id_profile')
    # ### end Alembic commands ###
