"""empty message

Revision ID: c02bb611c68f
Revises: 28ce67342c9a
Create Date: 2023-08-14 17:31:14.542716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02bb611c68f'
down_revision = '28ce67342c9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_deck_column_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_column', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('id_prompt', sa.Integer(), nullable=True),
    sa.Column('id_prompt_flow', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_column'], ['prompt_decks.id'], ),
    sa.ForeignKeyConstraint(['id_prompt'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['id_prompt_flow'], ['prompt_flows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('prompt_decks', sa.Column('is_archetype', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_decks', 'is_archetype')
    op.drop_table('prompt_deck_column_items')
    # ### end Alembic commands ###
