"""empty message

Revision ID: ca8e361799ce
Revises: 8009339250c0
Create Date: 2023-11-20 16:10:37.068713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8e361799ce'
down_revision = '8009339250c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_tags', sa.Column('raw_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_tags', 'raw_tag')
    # ### end Alembic commands ###
