"""empty message

Revision ID: db93c24c2f22
Revises: ba68fae3729b
Create Date: 2023-10-25 13:07:35.601927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db93c24c2f22'
down_revision = 'ba68fae3729b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_datum_context_responses', sa.Column('model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_datum_context_responses', 'model')
    # ### end Alembic commands ###
