"""empty message

Revision ID: eb97cd8b8d7f
Revises: 3ac6e43a319c
Create Date: 2023-09-22 14:59:05.455715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb97cd8b8d7f'
down_revision = '3ac6e43a319c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('id_str', sa.String(), nullable=True))
    op.add_column('nodes', sa.Column('id_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'id_str')
    op.drop_column('edges', 'id_str')
    # ### end Alembic commands ###
