"""empty message

Revision ID: f5f30f13b31d
Revises: c02bb611c68f
Create Date: 2023-08-14 17:34:57.266438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f30f13b31d'
down_revision = 'c02bb611c68f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_decks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('prompt_decks', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('prompt_decks', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_decks', 'description')
    op.drop_column('prompt_decks', 'subcategory')
    op.drop_column('prompt_decks', 'category')
    # ### end Alembic commands ###
