"""empty message

Revision ID: ff39aa49904b
Revises: 30f67deb3e6a
Create Date: 2023-10-19 11:47:42.589319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff39aa49904b'
down_revision = '30f67deb3e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_run_items', sa.Column('id_profile', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prompt_run_items', 'profiles', ['id_profile'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_run_items', type_='foreignkey')
    op.drop_column('prompt_run_items', 'id_profile')
    # ### end Alembic commands ###
